use rsi_common::model_control::{
    InvocationForeground, ModelInvocationKind, ModelInvocationPurpose, PaidRisk,
};

#[derive(Debug, Clone, Copy)]
pub struct RegistryEntry {
    pub purpose: ModelInvocationPurpose,
    pub kind: ModelInvocationKind,
    pub foreground: InvocationForeground,
    pub paid_risk: PaidRisk,
    pub trigger: &'static str,
    pub owner: &'static str,
    pub provider_model_resolution: &'static str,
    pub effort: &'static str,
    pub auth_billing_path: &'static str,
    pub current_entry_point: &'static str,
    pub backends: &'static str,
    pub current_guard: &'static str,
    pub budget_attribution_target: &'static str,
    pub concurrency: &'static str,
    pub cancellation: &'static str,
    pub persistence_restart: &'static str,
    pub observability: &'static str,
    pub current_budget_enforcement: &'static str,
    pub dedup_retry: &'static str,
    pub required_admission_hook: &'static str,
    pub accounting_hook: &'static str,
    pub emergency_control: &'static str,
    pub background_paid_enabled_by_default: bool,
}

impl RegistryEntry {
    pub const fn doc_purpose(self) -> &'static str {
        self.purpose.as_str()
    }
}

pub const REGISTRY: [RegistryEntry; 28] = [
    row(
        ModelInvocationPurpose::SessionLaunchFresh,
        ModelInvocationKind::SessionLifecycle,
        InvocationForeground::Foreground,
        PaidRisk::PaidCapable,
        "LaunchSession RPC, TUI launch, scheduled Fresh fallback",
        "spawned session, project, parent container",
        "LaunchConfig provider/model or project workflow defaults",
        "LaunchConfig.effort or provider default",
        "provider CLI uses the operator's local login/session; OpenAI-compatible/Harness paths use configured API key/base URL; local Ollama stays on localhost without paid billing",
        "crates/rsid/src/session/launch.rs:162",
        "provider launcher, Harness, CodexAppServer",
        "leaf-kind validation, sandbox allocation, spawn single-flight",
        "session, project, parent container",
        "one active launch per session id; provider/global policies may add more caps",
        "interrupt session / cancel launch",
        "session row persists; retries, continue, and rotation remint tokens after restart",
        "session row, events, turn metrics",
        "local guards only before this change",
        "session UUID plus explicit retry lineage",
        "before ProviderLauncher::launch or CodexAppServer start-turn",
        "create admitted ledger row before provider start; attach sessions.model_invocation_id",
        "deny-paid, stop-all",
        true,
    ),
    row(
        ModelInvocationPurpose::SessionContinueResume,
        ModelInvocationKind::SessionLifecycle,
        InvocationForeground::Foreground,
        PaidRisk::PaidCapable,
        "ContinueSession, AnswerQuestion, scheduled Resume, OnTerminal watch delivery",
        "existing session and continuation lineage",
        "stored session provider/model or reconstructed resume context",
        "stored effort or provider default",
        "same auth/billing path as the original session backend",
        "crates/rsid/src/session/lifecycle.rs:561",
        "provider launcher, Harness, CodexAppServer turn",
        "single-flight continue, terminal-state checks, retry cancellation",
        "session lineage",
        "single active resume per session id",
        "interrupt session / cancel continue",
        "completed-session row persists; scheduled resume/watch may replay after restart",
        "session row, events, turn metrics",
        "local guards only before this change",
        "session id and continuation turn context",
        "before resume provider launch/start_turn",
        "write a child ledger row tied to the resumed session lineage",
        "deny-paid, stop-all",
        true,
    ),
    row(
        ModelInvocationPurpose::SessionRetryAuto,
        ModelInvocationKind::SessionLifecycle,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "retry timer fire, restart retry requeue",
        "root session plus retry lineage",
        "inherits failed session provider/model",
        "inherits stored effort",
        "same auth/billing path as the failed session backend",
        "crates/rsid/src/session/lifecycle.rs:1703",
        "provider launcher, Harness, CodexAppServer retry path",
        "retry_enabled kill-switch, durable retry exhaustion, bounded retry dispatcher",
        "retry lineage and root session",
        "bounded retry dispatcher plus retry-scope budget",
        "CancelRetry, interrupt, continue, AgentHalt",
        "retry exhaustion survives restart; timer fires are replay-safe by lineage",
        "SessionRetrying events, session row, retry counters",
        "kind defaults and retry exhaustion only before this change",
        "session id plus retry attempt number",
        "at timer fire and again immediately before retry launch",
        "ledger row per retry child with retry_of_invocation_id",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::SessionRotateChild,
        ModelInvocationKind::SessionLifecycle,
        InvocationForeground::Foreground,
        PaidRisk::PaidCapable,
        "RotateSession and automatic context rotation",
        "rotation parent and child lineage",
        "inherits stored provider/model from the parent session",
        "inherits stored effort",
        "same auth/billing path as the rotated session backend",
        "crates/rsid/src/session/rotation.rs:1017",
        "provider launcher, Harness",
        "rotation lineage checks, spawn single-flight",
        "rotation lineage",
        "one child launch per rotation event",
        "interrupt child launch or child session",
        "rotation lineage persists across restart",
        "session rows, rotation events, bus events",
        "local rotation checks only before this change",
        "rotation child UUID",
        "before spawn_rotation_child launches the provider",
        "ledger row linked to continued_from parent session",
        "deny-paid, stop-all",
        true,
    ),
    row(
        ModelInvocationPurpose::SessionHarnessTurn,
        ModelInvocationKind::SessionLifecycle,
        InvocationForeground::Foreground,
        PaidRisk::PaidCapable,
        "Harness tool-loop follow-up provider call after the first admitted session execution",
        "existing harness-backed session lineage",
        "stored session model plus harness backend route resolution",
        "stored effort or provider default",
        "same auth/billing path as the harness-backed session backend",
        "crates/rsid/src/session/harness/agent_loop.rs:1",
        "Harness direct API",
        "per-call admission controller after the carried first permit is consumed",
        "session lineage",
        "one admitted backend call per loop iteration",
        "interrupt session / cancel turn",
        "child ledger rows persist across restart; unsettled rows reconcile conservatively",
        "session row, events, turn metrics, child invocation rows",
        "per-call store budget enforcement",
        "session id plus harness turn ordinal",
        "immediately before provider chat/stream_chat",
        "settle one ledger row per backend call",
        "deny-paid, stop-all",
        true,
    ),
    row(
        ModelInvocationPurpose::SessionHarnessCompaction,
        ModelInvocationKind::SessionLifecycle,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "Harness auto-compaction summary call",
        "existing harness-backed session lineage",
        "stored session model plus harness backend route resolution",
        "stored effort or provider default",
        "same auth/billing path as the harness-backed session backend",
        "crates/rsid/src/session/harness/compaction.rs:1",
        "Harness direct API",
        "per-call admission controller; local force-compaction remains non-invocation",
        "session lineage",
        "one admitted compaction call per compaction attempt",
        "interrupt session / cancel compaction",
        "child ledger rows persist across restart; denied compaction performs zero backend calls",
        "session row, events, compaction logs, child invocation rows",
        "per-call store budget enforcement",
        "session id plus compaction ordinal",
        "immediately before provider chat for compaction",
        "settle one ledger row per compaction attempt",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::SessionCodexAppServerTurn,
        ModelInvocationKind::SessionLifecycle,
        InvocationForeground::Foreground,
        PaidRisk::PaidCapable,
        "CodexAppServer turn/start after the first admitted session execution",
        "existing app-server-backed session lineage",
        "stored session model plus app-server transport route",
        "stored effort or provider default",
        "same auth/billing path as the app-server-backed session backend",
        "crates/rsid/src/codex_app_server.rs:187",
        "CodexAppServer turn/start",
        "per-turn admission controller after the carried first permit is consumed",
        "session lineage",
        "one admitted backend turn per turn/start request",
        "interrupt session / cancel turn",
        "child ledger rows persist across restart; unsettled rows reconcile conservatively",
        "session row, events, turn metrics, child invocation rows",
        "per-turn store budget enforcement",
        "session id plus turn ordinal",
        "immediately before each turn/start request",
        "settle one ledger row per turn/start",
        "deny-paid, stop-all",
        true,
    ),
    row(
        ModelInvocationPurpose::SessionOpenAiCompatibleTurn,
        ModelInvocationKind::SessionLifecycle,
        InvocationForeground::Foreground,
        PaidRisk::PaidCapable,
        "Local/OpenAI-compatible session tool-loop follow-up after the carried launch call",
        "existing Local-session lineage",
        "resolved OpenAI-compatible base URL and stored session model",
        "stored effort or provider default",
        "configured compatible endpoint and optional API key; the provider label follows the resolved transport",
        "crates/rsid/src/openai.rs:run_agentic_loop",
        "OpenAI-compatible streaming HTTP",
        "per-call admission controller after the carried first permit is consumed",
        "session lineage",
        "one admitted HTTP call per loop iteration",
        "interrupt session / cancel turn",
        "child invocation rows persist; abandoned settlements reconcile conservatively",
        "session events, turn metrics, child invocation rows",
        "per-call store budget enforcement",
        "session id plus compatible-turn ordinal",
        "immediately before each /chat/completions request",
        "settle one ledger row per HTTP attempt",
        "deny-paid, stop-all",
        true,
    ),
    row(
        ModelInvocationPurpose::AgentSpawnChild,
        ModelInvocationKind::Orchestration,
        InvocationForeground::Foreground,
        PaidRisk::PaidCapable,
        "AgentSpawnChild, native rsi_control_spawn, directive fallback",
        "epic lead session, child session, epic container",
        "requested child provider/model or emitter defaults",
        "requested child effort or emitter default",
        "same auth/billing path as ordinary spawned provider sessions",
        "crates/rsid/src/session/agent_verbs.rs:84",
        "provider launcher",
        "agent auth guard, spawn coordinator, idempotency key",
        "epic tree, caller, child",
        "spawn coordinator and tree/provider policies",
        "AgentHalt or session interrupt",
        "idempotency survives client retry; child row persists across restart",
        "session row, bus events, spawn coordinator state",
        "spawn rate limiting only before this change",
        "caller idempotency key plus child lineage",
        "before launch_session inside guarded child spawn",
        "ledger row for child session launch parented to the caller lineage",
        "deny-paid, stop-all",
        true,
    ),
    row(
        ModelInvocationPurpose::WorkflowGraphNode,
        ModelInvocationKind::Orchestration,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "ExecuteWorkflow and ExecuteTopology node dispatch",
        "workflow execution and node owner",
        "node provider/model with workflow fallback",
        "node effort or workflow default",
        "same auth/billing path as spawned provider session backends",
        "crates/rsid/src/session/graph_runner.rs:368",
        "provider launcher",
        "workflow state and node readiness only before this change",
        "workflow execution, node, project",
        "workflow fan-out plus provider/global caps",
        "interrupt workflow execution or node session",
        "workflow execution state persists across restart",
        "workflow execution state and session rows",
        "no unified budget enforcement before this change",
        "node id plus attempt number",
        "before each node LaunchConfig dispatch",
        "ledger row per node attempt",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::WorkflowChainIteration,
        ModelInvocationKind::Orchestration,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "StartChainedWorkflow and chain-driver requeue",
        "chain execution and iteration",
        "inherits node/session routing from workflow graph execution",
        "inherits node effort",
        "same auth/billing path as child workflow node launches",
        "crates/rsid/src/session/chain_driver.rs:45",
        "workflow graph node launches",
        "chain state and graph terminal event checks",
        "chain execution and iteration",
        "one active chain iteration per chain",
        "interrupt chain or child workflow execution",
        "chain state survives restart",
        "chain events and workflow session rows",
        "no unified budget enforcement before this change",
        "chain execution id and iteration",
        "before respawning the next chain iteration",
        "ledger row for the iteration plus child node rows",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::RecursiveLiveTask,
        ModelInvocationKind::Orchestration,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "RunRecursiveLiveScheduler and recursive live continuation",
        "recursive graph, task, attempt, scheduler run",
        "request params and recursive task metadata",
        "request effort or provider default",
        "same auth/billing path as spawned provider session backends",
        "crates/rsid/src/recursive_dag/live.rs:1649",
        "provider launcher",
        "recursive graph/task state and cancellation checks",
        "recursive graph and attempt lineage",
        "recursive attempt concurrency plus provider/global caps",
        "recursive cancellation request, interrupt, stop-all",
        "recursive live attempts and cancellation rows survive restart",
        "recursive live attempt rows, run events, session rows",
        "metadata-only budgets before this change",
        "attempt id and live attempt id",
        "before each live task launch and continuation",
        "ledger row per live attempt",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::ScheduledFresh,
        ModelInvocationKind::Background,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "scheduled Fresh job and Resume-without-target fallback",
        "scheduled job and produced session",
        "scheduled job provider/model",
        "scheduled job effort or provider default",
        "same auth/billing path as spawned provider session backends",
        "crates/rsid/src/scheduler/mod.rs:164",
        "provider launcher",
        "job enabled flag and due-time check",
        "scheduled job and produced session",
        "one fire per due slot plus provider/global caps",
        "disable job or interrupt produced session",
        "scheduled job row survives restart",
        "scheduled job state and produced session row",
        "hard-coded max_retries=3 only before this change",
        "job id plus due-fire slot",
        "before scheduler builds and launches a fresh LaunchConfig",
        "ledger row linked to scheduled_job_id",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::AgentScheduleWakeFresh,
        ModelInvocationKind::Background,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "token-resolved AgentScheduleWake and bound native schedule_wake Fresh job",
        "scheduled job, bound origin session, and produced session",
        "bound origin provider/model copied into the scheduled job",
        "scheduled job effort or provider default",
        "same auth/billing path as spawned provider session backends",
        "crates/rsid/src/scheduler/mod.rs:201",
        "provider launcher",
        "durable agent_fresh wake mode plus required origin lookup",
        "scheduled job, origin session, and produced session",
        "one fire per due slot plus provider/global caps",
        "disable one-shot job or interrupt produced session",
        "agent_fresh job row survives restart",
        "scheduled job state, model invocation, and produced session row",
        "Normal admits this explicit daemon-attributed background exception only",
        "job id plus due-fire slot",
        "before scheduler builds and launches a fresh LaunchConfig",
        "ledger row linked to scheduled_job_id",
        "deny-paid, pause-background, stop-all",
        true,
    ),
    row(
        ModelInvocationPurpose::ScheduledResumeWatch,
        ModelInvocationKind::Background,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "scheduled Resume and OnTerminal watch delivery",
        "scheduled job, watch target, resumed session",
        "stored provider/model of the resumed session",
        "stored session effort",
        "same auth/billing path as the resumed session backend",
        "crates/rsid/src/session/mod.rs:827",
        "provider launcher, CodexAppServer turn",
        "watch scoping and resumed-session status checks",
        "scheduled job and resumed session",
        "one delivery per watch plus provider/global caps",
        "disable watch or interrupt resumed session",
        "watch rows survive restart and may replay delivery",
        "scheduled job state, watch events, session row",
        "no unified budget enforcement before this change",
        "watch id plus wake target",
        "before resume_scheduled calls continue_session",
        "ledger row linked to scheduled_job_id and resumed session",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::IssueTrackerDispatch,
        ModelInvocationKind::Background,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "issue tracker poller dispatch",
        "issue tracker config, issue id, produced session",
        "issue tracker provider/model config",
        "tracker config effort or provider default",
        "same auth/billing path as spawned provider session backends",
        "crates/rsid/src/issue_tracker/poller.rs:191",
        "provider launcher",
        "tracker enabled flag and max_concurrent",
        "issue tracker, issue, project",
        "tracker max_concurrent plus provider/global caps",
        "disable tracker or interrupt produced session",
        "issue dispatch records survive restart",
        "issue dispatch rows and produced session rows",
        "tracker max_concurrent only before this change",
        "issue id plus dispatch attempt",
        "before poller calls session_launcher.launch",
        "ledger row linked to issue_tracker_id and issue_identifier",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::PromptCompile,
        ModelInvocationKind::DirectText,
        InvocationForeground::Foreground,
        PaidRisk::PaidCapable,
        "CompilePrompt RPC and prompt-compile cache miss",
        "caller id, project, prompt hash",
        "prompt-compile runtime defaults or request overrides",
        "none or request-level effort",
        "local Ollama uses localhost; paid OpenAI-compatible fallbacks use configured API key/base URL; CLI fallbacks inherit the operator login",
        "crates/rsid/src/prompt_compile/engine.rs:122",
        "Ollama generate, memory::llm fallback backends",
        "cache hit and supersede cancellation",
        "caller id, project, prompt hash",
        "one active compile per caller plus provider/global caps",
        "supersede cancellation",
        "cache and in-flight state are transient; ledger survives restart",
        "compile prompt bus events and cache",
        "cache/supersede only before this change",
        "prompt hash plus caller id",
        "before the cache-miss model call begins",
        "ledger row per cache miss or superseded compile",
        "deny-paid, stop-all",
        true,
    ),
    row(
        ModelInvocationPurpose::TextGenerateRpc,
        ModelInvocationKind::DirectText,
        InvocationForeground::Foreground,
        PaidRisk::PaidCapable,
        "GenerateText RPC and TUI text-generation caller",
        "operator or calling session",
        "RPC overrides or prompt-compile runtime defaults",
        "none",
        "local Ollama uses localhost; paid OpenAI-compatible fallbacks use configured API key/base URL; CLI fallbacks inherit the operator login",
        "crates/rsid/src/rpc.rs:5930",
        "Ollama generate, memory::llm backends",
        "RPC parameter validation",
        "operator or calling session",
        "one request per RPC plus provider/global caps",
        "request cancellation by caller disconnect or stop-all",
        "request is transient; ledger survives restart",
        "RPC response only before this change",
        "parameter validation only before this change",
        "request fingerprint if supplied",
        "before GenerateText model dispatch",
        "ledger row per GenerateText request",
        "deny-paid, stop-all",
        true,
    ),
    row(
        ModelInvocationPurpose::SessionTitle,
        ModelInvocationKind::Background,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "launch-time and finalize-time title/description generation",
        "session",
        "local title model or configured fallback provider/model",
        "none",
        "local Ollama uses localhost; CLI fallback uses the operator Claude login; OpenAI-compatible fallback uses configured base URL and API key",
        "crates/rsid/src/session/title.rs:130",
        "Ollama generate, Claude CLI fallback, memory::llm fallbacks",
        "empty-conversation and skip checks",
        "session",
        "one title generation per session phase",
        "skip, pause-background, stop-all",
        "title is transient unless persisted to session row; ledger survives restart",
        "session row title/description fields",
        "local skip checks only before this change",
        "session id plus title phase",
        "before native Ollama or fallback model call",
        "ledger row tied to session_id",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::SessionSummary,
        ModelInvocationKind::Background,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "monitor threshold summarization",
        "session",
        "local memory model or configured fallback provider/model",
        "none",
        "local Ollama uses localhost; paid fallback uses configured base URL and API key or CLI login",
        "crates/rsid/src/session/summarizer.rs:194",
        "Ollama generate, memory::llm fallbacks",
        "threshold and debounce checks",
        "session",
        "one summary task per debounce window",
        "pause-background, stop-all",
        "summary rows persist; in-flight task is transient",
        "session_summaries table and monitor logs",
        "debounce only before this change",
        "session id plus summary window",
        "before fallback model call",
        "ledger row tied to session_id and summary kind",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::MemoryObservationExtract,
        ModelInvocationKind::Background,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "memory worker observation extraction for completed sessions",
        "session and project memory index",
        "local memory model or configured fallback provider/model",
        "none",
        "local Ollama uses localhost; paid fallback uses configured base URL and API key or CLI login",
        "crates/rsid/src/observation/extractor.rs:123",
        "Ollama generate, memory::llm fallbacks",
        "event-count and extractable-text checks",
        "session and project memory",
        "one extraction window at a time",
        "pause-background, stop-all",
        "observation rows persist; worker task may replay after restart",
        "observation rows and memory worker logs",
        "min-event gating only before this change",
        "session id plus extraction window hash",
        "before fallback model call",
        "ledger row tied to session_id and project_id",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::MemoryEmbeddingIndex,
        ModelInvocationKind::Embedding,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "memory sync embedding provider selection and embedding batches",
        "project memory index and embedding batch",
        "memory embedding config and auto-fallback selection",
        "none",
        "local Ollama embedding uses localhost; paid fallback uses configured embedding URL/API key",
        "crates/rsid/src/memory/embedding/mod.rs:94",
        "Ollama embeddings, OpenAI-compatible embeddings",
        "provider availability probe only before this change",
        "project memory index and embedding batch",
        "batch-level concurrency plus provider/global caps",
        "pause-background, stop-all",
        "memory index persists; batches may replay after restart",
        "memory provider status and sync logs",
        "provider availability only before this change",
        "embedding batch id or chunk hash",
        "when selecting a paid-capable provider and before each batch request",
        "ledger row with embedding_input_count and project_id",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::DreamConsolidation,
        ModelInvocationKind::Background,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "automatic Dream scheduler and manual TriggerDream RPC",
        "global Dream subsystem, project memory, per-phase execution",
        "dream runtime config provider/model",
        "none",
        "local-only Dream uses localhost; paid Dream uses configured provider login or API key/base URL",
        "crates/rsid/src/dreamer/scheduler.rs:66",
        "memory::llm fallbacks through DreamerLlmClient",
        "dream_enabled flag, idle/session thresholds, cooldown",
        "Dream subsystem, project memory, per-phase batch",
        "single scheduler loop plus per-phase batch bounds",
        "dream shutdown, pause-background, stop-all",
        "dream state timestamp persists; active phase work must be idempotent across restart",
        "DreamStarted/DreamCompleted events and dream_state rows",
        "dream_enabled, threshold, cooldown only before this change",
        "dream run id plus phase name",
        "before each Dream phase model call",
        "ledger row per phase invocation",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::StallClassifier,
        ModelInvocationKind::Background,
        InvocationForeground::Background,
        PaidRisk::PaidCapable,
        "stall detector sibling scheduler",
        "classified session",
        "stall classifier runtime config model and API endpoint",
        "none",
        "OpenAI-compatible chat endpoint using configured URL and API key, or localhost local model",
        "crates/rsid/src/stall_classifier/scheduler.rs:133",
        "direct /chat/completions POST",
        "stall_classifier_enabled and per-session cooldown/count",
        "session and stall-classifier subsystem",
        "bounded classifier channel and per-session max count",
        "disable classifier, pause-background, stop-all",
        "classifier state on the tracked session persists via session row fields",
        "SessionClassified events and stall-classifier logs",
        "enabled/cooldown/max_count only before this change",
        "session id plus classification count",
        "before complete() posts to the classifier endpoint",
        "ledger row tied to session_id",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::DialecticQuery,
        ModelInvocationKind::DirectText,
        InvocationForeground::Foreground,
        PaidRisk::PaidCapable,
        "QueryMemory dialectic engine",
        "query caller and project scope",
        "dialectic runtime config model and API endpoint",
        "none",
        "OpenAI-compatible chat endpoint using configured URL and API key, or localhost local model",
        "crates/rsid/src/dialectic/mod.rs:118",
        "direct /chat/completions POST",
        "dialectic_enabled flag and max iteration count",
        "query caller and project",
        "iteration count plus provider/global caps",
        "RPC cancellation, deny-paid, stop-all",
        "query is transient; ledger survives restart for audit",
        "QueryMemory result and tool-call count",
        "enabled/max_iteration only before this change",
        "query id plus iteration index",
        "before each dialectic chat-completion round",
        "ledger row per iteration or per whole query",
        "deny-paid, stop-all",
        true,
    ),
    row(
        ModelInvocationPurpose::ModelDiscoveryClaudeProbe,
        ModelInvocationKind::Discovery,
        InvocationForeground::Foreground,
        PaidRisk::CatalogOnly,
        "DiscoverModels Claude catalog lookup",
        "operator model picker",
        "static Claude catalog",
        "none",
        "none; catalog discovery does not authenticate or bill",
        "crates/rsid/src/claude.rs:194",
        "no backend process or HTTP call",
        "catalog-only",
        "operator model picker",
        "none",
        "not applicable",
        "catalog is compiled into the daemon",
        "DiscoverModels response and logs",
        "not applicable",
        "not applicable",
        "not applicable; discovery starts no provider",
        "none",
        "not applicable",
        false,
    ),
    row(
        ModelInvocationPurpose::QueueDeferredModelTask,
        ModelInvocationKind::Queue,
        InvocationForeground::Background,
        PaidRisk::NonInvocation,
        "future queue processor registration for model-backed task types",
        "queued task owner",
        "future processor-specific resolution",
        "future processor-specific effort",
        "future processor-specific provider auth/billing path",
        "crates/rsid/src/queue/processor.rs:20",
        "no-op today; future model processors",
        "NoOpProcessor only today",
        "queued task owner",
        "queue worker plus provider/global caps once enabled",
        "queue cancellation, pause-background, stop-all",
        "queue rows persist across restart",
        "queue metrics only today",
        "none before this change because processors are no-op",
        "queue task id",
        "before any future model-capable processor executes",
        "ledger row per queued model task once implemented",
        "deny-paid, pause-background, stop-all",
        false,
    ),
    row(
        ModelInvocationPurpose::AgentReserveSuccessor,
        ModelInvocationKind::Orchestration,
        InvocationForeground::Foreground,
        PaidRisk::PaidCapable,
        "AgentReserveSuccessor and native rsi_control_reserve_successor",
        "authenticated Epic lead and daemon-authored successor reservation",
        "requested successor model or predecessor model",
        "requested successor effort or predecessor effort",
        "same auth/billing path as the inherited predecessor provider",
        "crates/rsid/src/session/agent_verbs.rs",
        "provider launcher after durable successor reservation",
        "agent auth guard, durable replay key, lead-generation fence",
        "owning Epic, predecessor, stable successor candidate",
        "one active reservation per predecessor replay key",
        "reservation failure or successor reconciliation settlement",
        "reservation, invocation, and transition rows survive restart",
        "successor reservation transitions and session events",
        "model admission before the stable candidate launch",
        "predecessor plus caller idempotency-key digest",
        "before launching the reserved successor candidate",
        "stable invocation row linked to the successor reservation",
        "deny-paid, stop-all",
        true,
    ),
];

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum PrimitiveKind {
    CliSpawn,
    HttpPost,
    RawHttpSend,
    ProviderChat,
    AppServerModelRequest,
    Unknown,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CapabilityConsumption {
    BindCommandSpawn,
    BindHttpSend,
    BindHttpOrProviderChat,
    ProviderChatArgument,
    SendCodexAppServer,
}

/// Runtime route identity carried by a one-use execution capability.
///
/// This is deliberately narrower than the transport family: each purpose may
/// claim only a route reachable from its closed source catalog entry, and the
/// immediate sink checks the exact route before it can execute.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum RuntimeExecutionRoute {
    ClaudeCli,
    CodexCli,
    AntigravityCli,
    MemoryCli,
    LocalOpenAiCompatibleHttp,
    DialecticHttp,
    StallClassifierHttp,
    OpenAiEmbeddingHttp,
    OllamaEmbeddingQueryHttp,
    OllamaEmbeddingBatchHttp,
    HarnessOpenAiHttp,
    HarnessAnthropicHttp,
    SessionHarnessOpenAiHttp,
    SessionHarnessAnthropicHttp,
    CodexAppServer,
}

#[derive(Debug, Clone, Copy)]
pub struct ExecutionBoundaryContract {
    pub id: &'static str,
    pub path: &'static str,
    pub item: &'static str,
    pub capability_type: &'static str,
    pub capability_ident: &'static str,
    pub primitive_kind: PrimitiveKind,
    pub consumption: CapabilityConsumption,
    pub runtime_route: RuntimeExecutionRoute,
    pub occurrences: usize,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AllowedExclusionOperation {
    CatalogOnly,
    HttpGetProbe,
    TcpProbe,
    TransportSpawn,
    LoopbackModelPost,
    NonModelHttpPost,
    QueueNoOp,
}

impl AllowedExclusionOperation {
    pub const fn description(self) -> &'static str {
        match self {
            Self::CatalogOnly => {
                "Named catalog operation; no model POST, provider chat, model CLI spawn, or AppServer model request."
            }
            Self::HttpGetProbe => "One source-bound HTTP GET and send; no paid sink family.",
            Self::TcpProbe => "One source-bound TCP availability probe; no paid sink family.",
            Self::TransportSpawn => {
                "One `codex app-server` transport spawn; no model request primitive."
            }
            Self::LoopbackModelPost => {
                "One POST whose URL is the value returned by `ollama_url()`; no other paid sink family."
            }
            Self::NonModelHttpPost => {
                "One source-bound non-model HTTP POST/send operation; no model endpoint or provider primitive."
            }
            Self::QueueNoOp => "Explicit `Ok(())` no-op queue completion; no paid sink family.",
        }
    }
}

#[derive(Debug, Clone, Copy)]
pub struct NonInvocationContract {
    pub id: &'static str,
    pub path: &'static str,
    pub item: &'static str,
    pub allowed_operation: AllowedExclusionOperation,
    pub proof_ident: &'static str,
    pub occurrences: usize,
}

#[derive(Debug, Clone, Copy)]
pub enum ExecutionRoute {
    Boundaries(&'static [&'static str]),
    Excluded(&'static str),
}

const HARNESS_BOUNDARIES: &[&str] = &[
    "harness_openai_chat",
    "harness_openai_stream",
    "harness_anthropic_chat",
    "harness_anthropic_stream",
    "session_harness_openai_chat",
    "session_harness_openai_stream",
    "session_harness_anthropic_chat",
    "session_harness_anthropic_stream",
];
const SESSION_BOUNDARIES: &[&str] = &[
    "claude_cli_launch",
    "codex_cli_launch",
    "antigravity_cli_launch",
    "local_openai_compatible_http",
    "harness_openai_chat",
    "harness_openai_stream",
    "harness_anthropic_chat",
    "harness_anthropic_stream",
    "session_harness_openai_chat",
    "session_harness_openai_stream",
    "session_harness_anthropic_chat",
    "session_harness_anthropic_stream",
    "appserver_model_request",
];
const MEMORY_BOUNDARIES: &[&str] = &[
    "memory_cli_launch",
    "session_harness_openai_chat",
    "session_harness_anthropic_chat",
];
const EMBEDDING_BOUNDARIES: &[&str] = &[
    "openai_embedding_http",
    "ollama_embedding_query_http",
    "ollama_embedding_batch_http",
];

pub const fn execution_route(purpose: ModelInvocationPurpose) -> ExecutionRoute {
    match purpose {
        ModelInvocationPurpose::SessionLaunchFresh
        | ModelInvocationPurpose::SessionContinueResume
        | ModelInvocationPurpose::SessionRetryAuto
        | ModelInvocationPurpose::SessionRotateChild
        | ModelInvocationPurpose::AgentSpawnChild
        | ModelInvocationPurpose::AgentReserveSuccessor
        | ModelInvocationPurpose::WorkflowGraphNode
        | ModelInvocationPurpose::WorkflowChainIteration
        | ModelInvocationPurpose::RecursiveLiveTask
        | ModelInvocationPurpose::ScheduledFresh
        | ModelInvocationPurpose::AgentScheduleWakeFresh
        | ModelInvocationPurpose::ScheduledResumeWatch
        | ModelInvocationPurpose::IssueTrackerDispatch => {
            ExecutionRoute::Boundaries(SESSION_BOUNDARIES)
        }
        ModelInvocationPurpose::SessionHarnessTurn
        | ModelInvocationPurpose::SessionHarnessCompaction => {
            ExecutionRoute::Boundaries(HARNESS_BOUNDARIES)
        }
        ModelInvocationPurpose::SessionCodexAppServerTurn => {
            ExecutionRoute::Boundaries(&["appserver_model_request"])
        }
        ModelInvocationPurpose::SessionOpenAiCompatibleTurn => {
            ExecutionRoute::Boundaries(&["local_openai_compatible_http"])
        }
        ModelInvocationPurpose::PromptCompile
        | ModelInvocationPurpose::TextGenerateRpc
        | ModelInvocationPurpose::SessionTitle
        | ModelInvocationPurpose::SessionSummary
        | ModelInvocationPurpose::MemoryObservationExtract
        | ModelInvocationPurpose::DreamConsolidation => {
            ExecutionRoute::Boundaries(MEMORY_BOUNDARIES)
        }
        ModelInvocationPurpose::MemoryEmbeddingIndex => {
            ExecutionRoute::Boundaries(EMBEDDING_BOUNDARIES)
        }
        ModelInvocationPurpose::StallClassifier => {
            ExecutionRoute::Boundaries(&["stall_classifier_http"])
        }
        ModelInvocationPurpose::DialecticQuery => ExecutionRoute::Boundaries(&["dialectic_http"]),
        ModelInvocationPurpose::ModelDiscoveryClaudeProbe => {
            ExecutionRoute::Excluded("claude_catalog")
        }
        ModelInvocationPurpose::QueueDeferredModelTask => ExecutionRoute::Excluded("queue_noop"),
    }
}

pub const EXECUTION_BOUNDARIES: &[ExecutionBoundaryContract] = &[
    boundary(
        "claude_cli_launch",
        "crates/rsid/src/claude.rs",
        "ClaudeClient::launch",
        "CliExecutionCapability",
        "execution",
        PrimitiveKind::CliSpawn,
        CapabilityConsumption::BindCommandSpawn,
        RuntimeExecutionRoute::ClaudeCli,
    ),
    boundary(
        "codex_cli_launch",
        "crates/rsid/src/codex.rs",
        "CodexClient::launch",
        "CliExecutionCapability",
        "execution",
        PrimitiveKind::CliSpawn,
        CapabilityConsumption::BindCommandSpawn,
        RuntimeExecutionRoute::CodexCli,
    ),
    boundary(
        "antigravity_cli_launch",
        "crates/rsid/src/agy.rs",
        "AgyClient::launch",
        "CliExecutionCapability",
        "execution",
        PrimitiveKind::CliSpawn,
        CapabilityConsumption::BindCommandSpawn,
        RuntimeExecutionRoute::AntigravityCli,
    ),
    boundary(
        "memory_cli_launch",
        "crates/rsid/src/memory/llm.rs",
        "run_cancellable_cli_with_killer",
        "CliExecutionCapability",
        "execution",
        PrimitiveKind::CliSpawn,
        CapabilityConsumption::BindCommandSpawn,
        RuntimeExecutionRoute::MemoryCli,
    ),
    boundary(
        "local_openai_compatible_http",
        "crates/rsid/src/openai.rs",
        "send_openai_chat_request",
        "ModelExecutionCapability",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::LocalOpenAiCompatibleHttp,
    ),
    boundary(
        "dialectic_http",
        "crates/rsid/src/dialectic/mod.rs",
        "DialecticEngine::send_admitted_request",
        "ModelExecutionCapability",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::DialecticHttp,
    ),
    boundary(
        "stall_classifier_http",
        "crates/rsid/src/stall_classifier/llm_client.rs",
        "StallClassifierLlmClient::complete",
        "ModelExecutionCapability",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::StallClassifierHttp,
    ),
    boundary(
        "openai_embedding_http",
        "crates/rsid/src/memory/embedding/openai_compat.rs",
        "OpenAiCompatEmbeddingProvider::call_api",
        "AdmittedEmbeddingExecution",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::OpenAiEmbeddingHttp,
    ),
    boundary(
        "ollama_embedding_query_http",
        "crates/rsid/src/memory/embedding/ollama.rs",
        "OllamaEmbeddingProvider::embed_single",
        "AdmittedEmbeddingExecution",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::OllamaEmbeddingQueryHttp,
    ),
    boundary(
        "ollama_embedding_batch_http",
        "crates/rsid/src/memory/embedding/ollama.rs",
        "OllamaEmbeddingProvider::embed_multiple",
        "AdmittedEmbeddingExecution",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::OllamaEmbeddingBatchHttp,
    ),
    boundary(
        "harness_openai_chat",
        "crates/rsid/src/harness/providers/openai_api.rs",
        "OpenAiApiProvider::chat",
        "ModelExecutionCapability",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::HarnessOpenAiHttp,
    ),
    boundary(
        "harness_openai_stream",
        "crates/rsid/src/harness/providers/openai_api.rs",
        "OpenAiApiProvider::stream_chat",
        "ModelExecutionCapability",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpOrProviderChat,
        RuntimeExecutionRoute::HarnessOpenAiHttp,
    ),
    boundary(
        "session_harness_openai_chat",
        "crates/rsid/src/session/harness/providers/openai_api.rs",
        "OpenAiApiProvider::chat",
        "ModelExecutionCapability",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::SessionHarnessOpenAiHttp,
    ),
    boundary(
        "session_harness_openai_stream",
        "crates/rsid/src/session/harness/providers/openai_api.rs",
        "OpenAiApiProvider::stream_chat",
        "ModelExecutionCapability",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpOrProviderChat,
        RuntimeExecutionRoute::SessionHarnessOpenAiHttp,
    ),
    boundary(
        "harness_anthropic_chat",
        "crates/rsid/src/harness/providers/anthropic.rs",
        "AnthropicProvider::chat",
        "ModelExecutionCapability",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::HarnessAnthropicHttp,
    ),
    boundary(
        "harness_anthropic_stream",
        "crates/rsid/src/harness/providers/anthropic.rs",
        "AnthropicProvider::stream_chat",
        "ModelExecutionCapability",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::HarnessAnthropicHttp,
    ),
    boundary(
        "session_harness_anthropic_chat",
        "crates/rsid/src/session/harness/providers/anthropic.rs",
        "AnthropicProvider::chat",
        "ModelExecutionCapability",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::SessionHarnessAnthropicHttp,
    ),
    boundary(
        "session_harness_anthropic_stream",
        "crates/rsid/src/session/harness/providers/anthropic.rs",
        "AnthropicProvider::stream_chat",
        "ModelExecutionCapability",
        "execution",
        PrimitiveKind::HttpPost,
        CapabilityConsumption::BindHttpSend,
        RuntimeExecutionRoute::SessionHarnessAnthropicHttp,
    ),
    ExecutionBoundaryContract {
        id: "appserver_model_request",
        path: "crates/rsid/src/codex_app_server.rs",
        item: "send_admitted_app_server_request",
        capability_type: "ModelExecutionCapability",
        capability_ident: "execution",
        primitive_kind: PrimitiveKind::AppServerModelRequest,
        consumption: CapabilityConsumption::SendCodexAppServer,
        runtime_route: RuntimeExecutionRoute::CodexAppServer,
        occurrences: 1,
    },
];

pub const NON_INVOCATIONS: &[NonInvocationContract] = &[
    exclusion(
        "appserver_transport_spawn",
        "crates/rsid/src/codex_app_server.rs",
        "CodexAppServerClient::launch",
        AllowedExclusionOperation::TransportSpawn,
        "app-server",
    ),
    exclusion(
        "claude_catalog",
        "crates/rsid/src/claude.rs",
        "ClaudeClient::discover_models",
        AllowedExclusionOperation::CatalogOnly,
        "append_catalog_family",
    ),
    exclusion(
        "codex_catalog",
        "crates/rsid/src/codex.rs",
        "CodexClient::discover_models",
        AllowedExclusionOperation::CatalogOnly,
        "discover_models_with_reason",
    ),
    exclusion(
        "codex_config_read",
        "crates/rsid/src/codex.rs",
        "probe_codex_configured_context_window",
        AllowedExclusionOperation::TransportSpawn,
        "app-server",
    ),
    exclusion(
        "antigravity_catalog",
        "crates/rsid/src/agy.rs",
        "AgyClient::discover_models",
        AllowedExclusionOperation::CatalogOnly,
        "openclaw",
    ),
    exclusion(
        "openai_catalog_get",
        "crates/rsid/src/openai.rs",
        "OpenAiClient::discover_models",
        AllowedExclusionOperation::HttpGetProbe,
        "models",
    ),
    exclusion(
        "openai_availability_probe",
        "crates/rsid/src/openai.rs",
        "OpenAiClient::is_local_available",
        AllowedExclusionOperation::TcpProbe,
        "127.0.0.1:11434",
    ),
    exclusion(
        "embedding_ollama_probe",
        "crates/rsid/src/memory/embedding/mod.rs",
        "probe_ollama",
        AllowedExclusionOperation::HttpGetProbe,
        "/api/tags",
    ),
    exclusion(
        "native_ollama_generate",
        "crates/rsid/src/ollama_client.rs",
        "generate",
        AllowedExclusionOperation::LoopbackModelPost,
        "ollama_url",
    ),
    exclusion(
        "native_ollama_stream",
        "crates/rsid/src/ollama_client.rs",
        "generate_stream",
        AllowedExclusionOperation::LoopbackModelPost,
        "ollama_url",
    ),
    exclusion(
        "native_ollama_warmup",
        "crates/rsid/src/ollama_client.rs",
        "warmup",
        AllowedExclusionOperation::LoopbackModelPost,
        "ollama_url",
    ),
    exclusion(
        "linear_graphql_post",
        "crates/rsid/src/issue_tracker/linear.rs",
        "LinearClient::graphql",
        AllowedExclusionOperation::NonModelHttpPost,
        "LINEAR_API_URL",
    ),
    exclusion(
        "queue_noop",
        "crates/rsid/src/queue/processor.rs",
        "NoOpProcessor::process",
        AllowedExclusionOperation::QueueNoOp,
        "Ok",
    ),
];

const fn boundary(
    id: &'static str,
    path: &'static str,
    item: &'static str,
    capability_type: &'static str,
    capability_ident: &'static str,
    primitive_kind: PrimitiveKind,
    consumption: CapabilityConsumption,
    runtime_route: RuntimeExecutionRoute,
) -> ExecutionBoundaryContract {
    ExecutionBoundaryContract {
        id,
        path,
        item,
        capability_type,
        capability_ident,
        primitive_kind,
        consumption,
        runtime_route,
        occurrences: 1,
    }
}

pub fn purpose_allows_runtime_route(
    purpose: ModelInvocationPurpose,
    runtime_route: RuntimeExecutionRoute,
) -> bool {
    let ExecutionRoute::Boundaries(ids) = execution_route(purpose) else {
        return false;
    };
    ids.iter().any(|id| {
        EXECUTION_BOUNDARIES
            .iter()
            .any(|contract| contract.id == *id && contract.runtime_route == runtime_route)
    })
}

const fn exclusion(
    id: &'static str,
    path: &'static str,
    item: &'static str,
    allowed_operation: AllowedExclusionOperation,
    proof_ident: &'static str,
) -> NonInvocationContract {
    NonInvocationContract {
        id,
        path,
        item,
        allowed_operation,
        proof_ident,
        occurrences: 1,
    }
}

/// Closed source registry lookup.
///
/// The exhaustive match makes a newly added purpose a compile error until it
/// receives a row. The fixed-size array makes a row addition/removal a compile
/// error, and the identity test below catches accidental index reuse.
pub const fn entry(purpose: ModelInvocationPurpose) -> &'static RegistryEntry {
    match purpose {
        ModelInvocationPurpose::SessionLaunchFresh => &REGISTRY[0],
        ModelInvocationPurpose::SessionContinueResume => &REGISTRY[1],
        ModelInvocationPurpose::SessionRetryAuto => &REGISTRY[2],
        ModelInvocationPurpose::SessionRotateChild => &REGISTRY[3],
        ModelInvocationPurpose::SessionHarnessTurn => &REGISTRY[4],
        ModelInvocationPurpose::SessionHarnessCompaction => &REGISTRY[5],
        ModelInvocationPurpose::SessionCodexAppServerTurn => &REGISTRY[6],
        ModelInvocationPurpose::SessionOpenAiCompatibleTurn => &REGISTRY[7],
        ModelInvocationPurpose::AgentSpawnChild => &REGISTRY[8],
        ModelInvocationPurpose::WorkflowGraphNode => &REGISTRY[9],
        ModelInvocationPurpose::WorkflowChainIteration => &REGISTRY[10],
        ModelInvocationPurpose::RecursiveLiveTask => &REGISTRY[11],
        ModelInvocationPurpose::ScheduledFresh => &REGISTRY[12],
        ModelInvocationPurpose::AgentScheduleWakeFresh => &REGISTRY[13],
        ModelInvocationPurpose::ScheduledResumeWatch => &REGISTRY[14],
        ModelInvocationPurpose::IssueTrackerDispatch => &REGISTRY[15],
        ModelInvocationPurpose::PromptCompile => &REGISTRY[16],
        ModelInvocationPurpose::TextGenerateRpc => &REGISTRY[17],
        ModelInvocationPurpose::SessionTitle => &REGISTRY[18],
        ModelInvocationPurpose::SessionSummary => &REGISTRY[19],
        ModelInvocationPurpose::MemoryObservationExtract => &REGISTRY[20],
        ModelInvocationPurpose::MemoryEmbeddingIndex => &REGISTRY[21],
        ModelInvocationPurpose::DreamConsolidation => &REGISTRY[22],
        ModelInvocationPurpose::StallClassifier => &REGISTRY[23],
        ModelInvocationPurpose::DialecticQuery => &REGISTRY[24],
        ModelInvocationPurpose::ModelDiscoveryClaudeProbe => &REGISTRY[25],
        ModelInvocationPurpose::QueueDeferredModelTask => &REGISTRY[26],
        ModelInvocationPurpose::AgentReserveSuccessor => &REGISTRY[27],
    }
}

pub const fn lookup(purpose: ModelInvocationPurpose) -> Option<&'static RegistryEntry> {
    Some(entry(purpose))
}

pub fn render_markdown_table() -> String {
    let mut out = String::from(
        "| Purpose ID | Trigger | Owner | Foreground/background | Provider/model resolution | Effort | Authentication/billing path | Current entry point | Backend(s) | Paid risk | Current guard | Budget / attribution target | Concurrency | Cancellation | Persistence/restart | Observability | Current budget enforcement | Dedup / retry | Required admission hook | Accounting hook | Emergency control |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |\n",
    );
    for entry in REGISTRY {
        let row = format!(
            "| `{}` | {} | {} | {} | {} | {} | {} | `{}` | {} | `{}` | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} | {} |\n",
            entry.doc_purpose(),
            entry.trigger,
            entry.owner,
            match entry.foreground {
                InvocationForeground::Foreground => "foreground",
                InvocationForeground::Background => "background",
            },
            entry.provider_model_resolution,
            entry.effort,
            entry.auth_billing_path,
            entry.current_entry_point,
            entry.backends,
            match entry.paid_risk {
                PaidRisk::PaidCapable => "paid-capable",
                PaidRisk::LocalOnly => "local-only",
                PaidRisk::CatalogOnly => "catalog-only",
                PaidRisk::NonInvocation => "non-invocation",
            },
            entry.current_guard,
            entry.budget_attribution_target,
            entry.concurrency,
            entry.cancellation,
            entry.persistence_restart,
            entry.observability,
            entry.current_budget_enforcement,
            entry.dedup_retry,
            entry.required_admission_hook,
            entry.accounting_hook,
            entry.emergency_control,
        );
        out.push_str(&row);
    }
    out
}

pub fn render_exclusion_markdown_table() -> String {
    let mut out = String::from(
        "| Contract ID | Source item | Structurally allowed operation |\n| --- | --- | --- |\n",
    );
    for contract in NON_INVOCATIONS {
        out.push_str(&format!(
            "| `{}` | `{}` | {} Proof identity: `{}`. |\n",
            contract.id,
            contract.item,
            contract.allowed_operation.description(),
            contract.proof_ident,
        ));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    const PURPOSES: &[ModelInvocationPurpose] = &[
        ModelInvocationPurpose::SessionLaunchFresh,
        ModelInvocationPurpose::SessionContinueResume,
        ModelInvocationPurpose::SessionRetryAuto,
        ModelInvocationPurpose::SessionRotateChild,
        ModelInvocationPurpose::SessionHarnessTurn,
        ModelInvocationPurpose::SessionHarnessCompaction,
        ModelInvocationPurpose::SessionCodexAppServerTurn,
        ModelInvocationPurpose::SessionOpenAiCompatibleTurn,
        ModelInvocationPurpose::AgentSpawnChild,
        ModelInvocationPurpose::WorkflowGraphNode,
        ModelInvocationPurpose::WorkflowChainIteration,
        ModelInvocationPurpose::RecursiveLiveTask,
        ModelInvocationPurpose::ScheduledFresh,
        ModelInvocationPurpose::AgentScheduleWakeFresh,
        ModelInvocationPurpose::ScheduledResumeWatch,
        ModelInvocationPurpose::IssueTrackerDispatch,
        ModelInvocationPurpose::PromptCompile,
        ModelInvocationPurpose::TextGenerateRpc,
        ModelInvocationPurpose::SessionTitle,
        ModelInvocationPurpose::SessionSummary,
        ModelInvocationPurpose::MemoryObservationExtract,
        ModelInvocationPurpose::MemoryEmbeddingIndex,
        ModelInvocationPurpose::DreamConsolidation,
        ModelInvocationPurpose::StallClassifier,
        ModelInvocationPurpose::DialecticQuery,
        ModelInvocationPurpose::ModelDiscoveryClaudeProbe,
        ModelInvocationPurpose::QueueDeferredModelTask,
        ModelInvocationPurpose::AgentReserveSuccessor,
    ];

    #[test]
    fn registry_rows_are_total_unique_and_identity_mapped() {
        assert_eq!(REGISTRY.len(), PURPOSES.len(), "no default/sentinel rows");
        let rows = REGISTRY
            .iter()
            .map(|row| row.purpose)
            .collect::<HashSet<_>>();
        assert_eq!(
            rows.len(),
            REGISTRY.len(),
            "registry purpose rows must be unique"
        );
        for purpose in PURPOSES {
            assert_eq!(entry(*purpose).purpose, *purpose);
        }
    }

    #[test]
    fn agent_schedule_wake_fresh_is_the_only_default_enabled_paid_background_purpose() {
        let enabled: Vec<_> = REGISTRY
            .iter()
            .filter(|entry| {
                entry.foreground == InvocationForeground::Background
                    && entry.paid_risk == PaidRisk::PaidCapable
                    && entry.background_paid_enabled_by_default
            })
            .map(|entry| entry.purpose)
            .collect();
        assert_eq!(
            enabled,
            vec![ModelInvocationPurpose::AgentScheduleWakeFresh]
        );
    }
}

const fn row(
    purpose: ModelInvocationPurpose,
    kind: ModelInvocationKind,
    foreground: InvocationForeground,
    paid_risk: PaidRisk,
    trigger: &'static str,
    owner: &'static str,
    provider_model_resolution: &'static str,
    effort: &'static str,
    auth_billing_path: &'static str,
    current_entry_point: &'static str,
    backends: &'static str,
    current_guard: &'static str,
    budget_attribution_target: &'static str,
    concurrency: &'static str,
    cancellation: &'static str,
    persistence_restart: &'static str,
    observability: &'static str,
    current_budget_enforcement: &'static str,
    dedup_retry: &'static str,
    required_admission_hook: &'static str,
    accounting_hook: &'static str,
    emergency_control: &'static str,
    background_paid_enabled_by_default: bool,
) -> RegistryEntry {
    RegistryEntry {
        purpose,
        kind,
        foreground,
        paid_risk,
        trigger,
        owner,
        provider_model_resolution,
        effort,
        auth_billing_path,
        current_entry_point,
        backends,
        current_guard,
        budget_attribution_target,
        concurrency,
        cancellation,
        persistence_restart,
        observability,
        current_budget_enforcement,
        dedup_retry,
        required_admission_hook,
        accounting_hook,
        emergency_control,
        background_paid_enabled_by_default,
    }
}
