//! Standalone HTML writer for the manual model.
//!
//! Covers headings, paragraphs, inline code, bold, tables and escaping, with
//! one embedded stylesheet and a print page break per chapter. No JavaScript,
//! no external assets.

use std::fmt::Write as _;

use super::model::{Block, Manual, Table};

const STYLE: &str = "body{font:15px/1.5 system-ui,sans-serif;max-width:72rem;margin:2rem auto;padding:0 1rem;color:#1d1d1f;background:#fff}\
h1,h2,h3,h4{line-height:1.25}h2{border-bottom:1px solid #ccc;padding-bottom:.2rem;margin-top:2.5rem}\
table{border-collapse:collapse;width:100%;margin:.5rem 0 1.25rem;font-size:14px}\
th,td{border:1px solid #d0d0d0;padding:.3rem .5rem;text-align:left;vertical-align:top}\
th{background:#f2f2f2}code{font-family:ui-monospace,monospace;background:#f4f4f4;padding:0 .2rem;border-radius:3px}\
nav ol{columns:2}\
@media print{body{max-width:none;margin:0}section.chapter{break-before:page}nav{break-after:page}a{color:inherit;text-decoration:none}}";

fn escape(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    for c in text.chars() {
        match c {
            '&' => out.push_str("&amp;"),
            '<' => out.push_str("&lt;"),
            '>' => out.push_str("&gt;"),
            '"' => out.push_str("&quot;"),
            _ => out.push(c),
        }
    }
    out
}

/// Inline markup: `code` (single or double backtick spans) and **bold**.
fn inline(text: &str) -> String {
    let mut out = String::new();
    let mut rest = text;
    while !rest.is_empty() {
        if let Some(after) = rest.strip_prefix("`` ")
            && let Some(end) = after.find(" ``")
        {
            out.push_str("<code>");
            out.push_str(&escape(&after[..end]));
            out.push_str("</code>");
            rest = &after[end + 3..];
        } else if let Some(after) = rest.strip_prefix('`')
            && let Some(end) = after.find('`')
        {
            out.push_str("<code>");
            out.push_str(&escape(&after[..end]));
            out.push_str("</code>");
            rest = &after[end + 1..];
        } else if let Some(after) = rest.strip_prefix("**")
            && let Some(end) = after.find("**")
        {
            out.push_str("<strong>");
            out.push_str(&escape(&after[..end]));
            out.push_str("</strong>");
            rest = &after[end + 2..];
        } else {
            let next = rest
                .char_indices()
                .skip(1)
                .find(|(_, c)| *c == '`' || *c == '*')
                .map_or(rest.len(), |(index, _)| index);
            out.push_str(&escape(&rest[..next]));
            rest = &rest[next..];
        }
    }
    out
}

fn table(out: &mut String, table: &Table) {
    out.push_str("<table>\n<thead><tr>");
    for header in &table.headers {
        out.push_str("<th>");
        out.push_str(&escape(header));
        out.push_str("</th>");
    }
    out.push_str("</tr></thead>\n<tbody>\n");
    for row in &table.rows {
        out.push_str("<tr>");
        for cell in row {
            out.push_str("<td>");
            out.push_str(&inline(cell));
            out.push_str("</td>");
        }
        out.push_str("</tr>\n");
    }
    out.push_str("</tbody>\n</table>\n");
}

fn blocks_into(out: &mut String, blocks: &[Block]) {
    for block in blocks {
        match block {
            Block::Heading { level, text } => {
                let tag = if *level == 0 { "h3" } else { "h4" };
                let _ = writeln!(out, "<{tag}>{}</{tag}>", inline(text));
            }
            Block::Paragraph(text) => {
                out.push_str("<p>");
                out.push_str(&inline(text));
                out.push_str("</p>\n");
            }
            Block::Table(t) => table(out, t),
            Block::Region { id, blocks } => {
                let _ = writeln!(out, "<div class=\"region\" id=\"{}\">", escape(id));
                blocks_into(out, blocks);
                out.push_str("</div>\n");
            }
        }
    }
}

/// Render the whole manual as one standalone HTML document.
#[must_use]
pub fn render(manual: &Manual) -> String {
    let mut out = String::new();
    out.push_str("<!DOCTYPE html>\n<!-- Generated by `make manual` from the rsi registries. Do not edit by hand. -->\n");
    out.push_str("<html lang=\"en\">\n<head>\n<meta charset=\"utf-8\">\n<title>rsi Operator Manual</title>\n<style>");
    out.push_str(STYLE);
    out.push_str("</style>\n</head>\n<body>\n<h1>rsi Operator Manual</h1>\n");
    out.push_str("<p>Generated from the rsi registries: the action registry, key tables, overlay help catalog, settings registry and theme table. Regenerate with <code>make manual</code>; print to PDF from the browser.</p>\n");
    out.push_str("<nav><h2>Contents</h2>\n<ol>\n");
    for chapter in &manual.chapters {
        let _ = writeln!(
            out,
            "<li><a href=\"#{}\">{}</a></li>",
            chapter.id,
            escape(chapter.title)
        );
    }
    out.push_str("</ol>\n</nav>\n");
    for (index, chapter) in manual.chapters.iter().enumerate() {
        let _ = writeln!(
            out,
            "<section class=\"chapter\" id=\"{}\">\n<h2>{}. {}</h2>\n<p>{}</p>",
            chapter.id,
            index + 1,
            escape(chapter.title),
            inline(chapter.intro)
        );
        blocks_into(&mut out, &chapter.blocks);
        out.push_str("</section>\n");
    }
    out.push_str("</body>\n</html>\n");
    out
}
