//! Markdown writer for the manual model.

use std::fmt::Write as _;

use super::model::{Block, Manual, Table};

pub const GENERATED_NOTICE: &str =
    "<!-- Generated by `make manual` from the rsi registries. Do not edit by hand. -->";

/// Escape a table cell: pipes split cells and newlines end rows.
fn cell(text: &str) -> String {
    text.replace('|', "\\|").replace('\n', " ")
}

pub fn table(out: &mut String, table: &Table) {
    out.push_str("| ");
    out.push_str(&table.headers.join(" | "));
    out.push_str(" |\n|");
    for _ in &table.headers {
        out.push_str(" --- |");
    }
    out.push('\n');
    for row in &table.rows {
        out.push_str("| ");
        out.push_str(
            &row.iter()
                .map(|text| cell(text))
                .collect::<Vec<_>>()
                .join(" | "),
        );
        out.push_str(" |\n");
    }
}

/// Render a region body (paragraphs and tables only).
#[must_use]
pub fn region_body(blocks: &[Block]) -> String {
    let mut out = String::new();
    blocks_into(&mut out, blocks, 3);
    out.trim_end().to_string()
}

fn blocks_into(out: &mut String, blocks: &[Block], base_level: usize) {
    for block in blocks {
        match block {
            Block::Heading { level, text } => {
                out.push_str(&"#".repeat(base_level + usize::from(*level)));
                out.push(' ');
                out.push_str(text);
                out.push_str("\n\n");
            }
            Block::Paragraph(text) => {
                out.push_str(text);
                out.push_str("\n\n");
            }
            Block::Table(t) => {
                table(out, t);
                out.push('\n');
            }
            Block::Region { blocks, .. } => blocks_into(out, blocks, base_level),
        }
    }
}

/// Render the whole manual.
#[must_use]
pub fn render(manual: &Manual) -> String {
    let mut out = String::new();
    out.push_str(GENERATED_NOTICE);
    out.push_str("\n\n# rsi Operator Manual\n\n");
    out.push_str("Generated from the rsi registries: the action registry, key tables, overlay help catalog, settings registry and theme table. Regenerate with `make manual`.\n\n");
    out.push_str("## Contents\n\n");
    for (index, chapter) in manual.chapters.iter().enumerate() {
        let _ = writeln!(out, "{}. {}", index + 1, chapter.title);
    }
    out.push('\n');
    for (index, chapter) in manual.chapters.iter().enumerate() {
        let _ = write!(out, "## {}. {}\n\n", index + 1, chapter.title);
        out.push_str(chapter.intro);
        out.push_str("\n\n");
        blocks_into(&mut out, &chapter.blocks, 3);
    }
    out.trim_end().to_string() + "\n"
}
