//! Observation CRUD operations in flywheel.db for the Dreamer system.
//!
//! Observations extracted from sessions (explicit) or generated by the dreamer
//! (deductive, inductive, contradiction) are stored here alongside sessions.

use crate::error::Result;
use crate::store::Store;
use chrono::Utc;
use rsi_common::types::{Observation, ObservationConfidence, ObservationLevel};
use rusqlite::params;
use uuid::Uuid;

impl Store {
    /// Insert a single observation.
    pub fn insert_observation(&self, obs: &Observation) -> Result<()> {
        let source_ids_json = serde_json::to_string(&obs.source_ids).unwrap_or_default();
        let now = Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Nanos, true);
        self.conn.execute(
            "INSERT INTO observations (id, session_id, project_id, level, content, source_ids, confidence, times_derived, created_at, updated_at)
             VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10)
             ON CONFLICT(id) DO UPDATE SET
                 content = excluded.content,
                 times_derived = excluded.times_derived,
                 updated_at = excluded.updated_at",
            params![
                obs.id.to_string(),
                obs.session_id.to_string(),
                obs.project_id.map(|id| id.to_string()),
                level_to_str(obs.level),
                obs.content,
                source_ids_json,
                obs.confidence.map(confidence_to_str),
                obs.times_derived,
                now,
                now,
            ],
        )?;
        Ok(())
    }

    /// Batch insert observations.
    pub fn insert_observations_batch(&self, observations: &[Observation]) -> Result<()> {
        if observations.is_empty() {
            return Ok(());
        }
        for obs in observations {
            self.insert_observation(obs)?;
        }
        Ok(())
    }

    /// List observations filtered by level, excluding soft-deleted.
    pub fn list_observations_by_level(
        &self,
        level: ObservationLevel,
        limit: usize,
    ) -> Result<Vec<Observation>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, session_id, project_id, level, content, source_ids, confidence, times_derived, created_at, updated_at
             FROM observations
             WHERE level = ?1 AND deleted_at IS NULL
             ORDER BY created_at DESC
             LIMIT ?2",
        )?;

        let rows = stmt
            .query_map(
                params![level_to_str(level), limit as i64],
                map_observation_row,
            )?
            .filter_map(|r| r.ok())
            .collect();

        Ok(rows)
    }

    /// List observations filtered by project, excluding soft-deleted.
    pub fn list_observations_by_project(&self, project_id: Uuid) -> Result<Vec<Observation>> {
        let mut stmt = self.conn.prepare(
            "SELECT id, session_id, project_id, level, content, source_ids, confidence, times_derived, created_at, updated_at
             FROM observations
             WHERE project_id = ?1 AND deleted_at IS NULL
             ORDER BY created_at DESC",
        )?;

        let rows = stmt
            .query_map(params![project_id.to_string()], map_observation_row)?
            .filter_map(|r| r.ok())
            .collect();

        Ok(rows)
    }

    /// List observations created after the last dream cycle timestamp.
    pub fn list_observations_since_last_dream(&self) -> Result<Vec<Observation>> {
        let last_dream = self.get_dream_state("last_dream_at")?;
        let since = last_dream.unwrap_or_else(|| "1970-01-01T00:00:00Z".to_string());

        let mut stmt = self.conn.prepare(
            "SELECT id, session_id, project_id, level, content, source_ids, confidence, times_derived, created_at, updated_at
             FROM observations
             WHERE created_at > ?1 AND deleted_at IS NULL
             ORDER BY created_at ASC",
        )?;

        let rows = stmt
            .query_map(params![since], map_observation_row)?
            .filter_map(|r| r.ok())
            .collect();

        Ok(rows)
    }

    /// Soft-delete an observation by ID.
    pub fn soft_delete_observation(&self, id: Uuid) -> Result<()> {
        let now = Utc::now().to_rfc3339_opts(chrono::SecondsFormat::Nanos, true);
        self.conn.execute(
            "UPDATE observations SET deleted_at = ?1, updated_at = ?1 WHERE id = ?2",
            params![now, id.to_string()],
        )?;
        Ok(())
    }

    /// Count non-deleted observations created after a given timestamp.
    pub fn count_observations_since(&self, since: chrono::DateTime<Utc>) -> Result<u64> {
        let since_str = since.to_rfc3339_opts(chrono::SecondsFormat::Nanos, true);
        let count: i64 = self.conn.query_row(
            "SELECT COUNT(*) FROM observations WHERE created_at > ?1 AND deleted_at IS NULL",
            params![since_str],
            |row| row.get(0),
        )?;
        Ok(count as u64)
    }

    /// Count total non-deleted observations in the main store.
    pub fn count_all_observations(&self) -> Result<u64> {
        let count: i64 = self.conn.query_row(
            "SELECT COUNT(*) FROM observations WHERE deleted_at IS NULL",
            [],
            |row| row.get(0),
        )?;
        Ok(count as u64)
    }

    /// Most recent persisted foreground session activity timestamp.
    pub fn latest_session_activity_at(&self) -> Result<Option<chrono::DateTime<Utc>>> {
        let raw: Option<String> =
            self.conn
                .query_row("SELECT MAX(updated_at) FROM sessions", [], |row| row.get(0))?;
        raw.map(|value| {
            chrono::DateTime::parse_from_rfc3339(&value)
                .map(|dt| dt.with_timezone(&Utc))
                .map_err(|e| {
                    crate::error::DaemonError::Store(format!(
                        "invalid session updated_at timestamp '{value}': {e}"
                    ))
                })
        })
        .transpose()
    }

    /// List completed/archived sessions that have no explicit observations yet.
    pub fn sessions_needing_extraction(&self, limit: usize) -> Result<Vec<Uuid>> {
        let mut stmt = self.conn.prepare(
            "SELECT s.id FROM sessions s
             LEFT JOIN observations o ON o.session_id = s.id AND o.level = 'explicit' AND o.deleted_at IS NULL
             WHERE s.status IN ('Completed', 'Archived')
             AND o.id IS NULL
             ORDER BY s.updated_at DESC
             LIMIT ?1",
        )?;
        let ids: Vec<Uuid> = stmt
            .query_map(params![limit as i64], |row| {
                let id_str: String = row.get(0)?;
                Ok(Uuid::parse_str(&id_str).unwrap_or_default())
            })?
            .filter_map(|r| r.ok())
            .filter(|id| !id.is_nil())
            .collect();
        Ok(ids)
    }

    // -------------------------------------------------------------------------
    // Dream State helpers
    // -------------------------------------------------------------------------

    /// Get a dream state value by key.
    pub fn get_dream_state(&self, key: &str) -> Result<Option<String>> {
        let result = self.conn.query_row(
            "SELECT value FROM dream_state WHERE key = ?1",
            params![key],
            |row| row.get::<_, String>(0),
        );
        match result {
            Ok(v) => Ok(Some(v)),
            Err(rusqlite::Error::QueryReturnedNoRows) => Ok(None),
            Err(e) => Err(e.into()),
        }
    }

    /// Set a dream state value (upsert).
    pub fn set_dream_state(&self, key: &str, value: &str) -> Result<()> {
        self.set_dream_state_at(key, value, Utc::now())
    }

    /// Set a dream state value (upsert) using an explicit timestamp.
    pub fn set_dream_state_at(
        &self,
        key: &str,
        value: &str,
        updated_at: chrono::DateTime<Utc>,
    ) -> Result<()> {
        let now = updated_at.to_rfc3339_opts(chrono::SecondsFormat::Nanos, true);
        self.conn.execute(
            "INSERT INTO dream_state (key, value, updated_at) VALUES (?1, ?2, ?3)
             ON CONFLICT(key) DO UPDATE SET value = excluded.value, updated_at = excluded.updated_at",
            params![key, value, now],
        )?;
        Ok(())
    }
}

// -------------------------------------------------------------------------
// Helpers
// -------------------------------------------------------------------------

fn level_to_str(level: ObservationLevel) -> &'static str {
    match level {
        ObservationLevel::Explicit => "explicit",
        ObservationLevel::Deductive => "deductive",
        ObservationLevel::Inductive => "inductive",
        ObservationLevel::Contradiction => "contradiction",
        _ => "explicit",
    }
}

fn str_to_level(s: &str) -> ObservationLevel {
    match s {
        "deductive" => ObservationLevel::Deductive,
        "inductive" => ObservationLevel::Inductive,
        "contradiction" => ObservationLevel::Contradiction,
        _ => ObservationLevel::Explicit,
    }
}

fn confidence_to_str(c: ObservationConfidence) -> &'static str {
    match c {
        ObservationConfidence::Low => "low",
        ObservationConfidence::Medium => "medium",
        ObservationConfidence::High => "high",
        _ => "low",
    }
}

fn str_to_confidence(s: &str) -> ObservationConfidence {
    match s {
        "medium" => ObservationConfidence::Medium,
        "high" => ObservationConfidence::High,
        _ => ObservationConfidence::Low,
    }
}

fn map_observation_row(row: &rusqlite::Row<'_>) -> rusqlite::Result<Observation> {
    let id_str: String = row.get(0)?;
    let session_id_str: String = row.get(1)?;
    let project_id_str: Option<String> = row.get(2)?;
    let level_str: String = row.get(3)?;
    let content: String = row.get(4)?;
    let source_ids_json: Option<String> = row.get(5)?;
    let confidence_str: Option<String> = row.get(6)?;
    let times_derived: u32 = row.get(7)?;
    let created_at_str: String = row.get(8)?;
    let updated_at_str: String = row.get(9)?;

    let id = Uuid::parse_str(&id_str).unwrap_or_default();
    let session_id = Uuid::parse_str(&session_id_str).unwrap_or_default();
    let project_id = project_id_str.and_then(|s| Uuid::parse_str(&s).ok());
    let level = str_to_level(&level_str);
    let source_ids: Vec<Uuid> = source_ids_json
        .and_then(|j| serde_json::from_str(&j).ok())
        .unwrap_or_default();
    let confidence = confidence_str.map(|s| str_to_confidence(&s));
    let created_at = chrono::DateTime::parse_from_rfc3339(&created_at_str)
        .map(|dt| dt.with_timezone(&Utc))
        .unwrap_or_else(|_| Utc::now());
    let updated_at = chrono::DateTime::parse_from_rfc3339(&updated_at_str)
        .map(|dt| dt.with_timezone(&Utc))
        .unwrap_or_else(|_| Utc::now());

    Ok(Observation {
        id,
        session_id,
        project_id,
        level,
        content,
        source_ids,
        confidence,
        times_derived,
        created_at,
        updated_at,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::store::Store;

    /// Opens the store inside a `TempDir` and returns the guard so the whole
    /// directory is removed when the test ends. A `NamedTempFile` is not
    /// sufficient here: SQLite writes `-wal` and `-shm` sidecars next to the
    /// database, and those paths are not covered by the file guard, so they
    /// are orphaned in `/tmp` when it drops.
    fn test_store() -> (tempfile::TempDir, Store) {
        let dir = tempfile::tempdir().unwrap();
        let store = Store::open(&dir.path().join("test.db")).unwrap();
        (dir, store)
    }

    #[test]
    fn test_insert_and_list_observation() {
        let (_dir, store) = test_store();
        let obs = Observation {
            id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            project_id: None,
            level: ObservationLevel::Explicit,
            content: "User prefers vim keybindings".to_string(),
            source_ids: vec![],
            confidence: None,
            times_derived: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        store.insert_observation(&obs).unwrap();

        let list = store
            .list_observations_by_level(ObservationLevel::Explicit, 100)
            .unwrap();
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].content, "User prefers vim keybindings");
        assert_eq!(list[0].id, obs.id);
    }

    #[test]
    fn test_soft_delete_observation() {
        let (_dir, store) = test_store();
        let obs = Observation {
            id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            project_id: None,
            level: ObservationLevel::Explicit,
            content: "test".to_string(),
            source_ids: vec![],
            confidence: None,
            times_derived: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        store.insert_observation(&obs).unwrap();

        store.soft_delete_observation(obs.id).unwrap();

        let list = store
            .list_observations_by_level(ObservationLevel::Explicit, 100)
            .unwrap();
        assert!(list.is_empty());
    }

    #[test]
    fn test_count_observations_since() {
        let (_dir, store) = test_store();
        let before = Utc::now();
        let obs = Observation {
            id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            project_id: None,
            level: ObservationLevel::Explicit,
            content: "test".to_string(),
            source_ids: vec![],
            confidence: None,
            times_derived: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        store.insert_observation(&obs).unwrap();

        let count = store.count_observations_since(before).unwrap();
        assert_eq!(count, 1);

        let future = Utc::now() + chrono::Duration::hours(1);
        let count = store.count_observations_since(future).unwrap();
        assert_eq!(count, 0);
    }

    #[test]
    fn test_dream_state_get_set() {
        let (_dir, store) = test_store();

        // Missing key returns None
        assert!(store.get_dream_state("nonexistent").unwrap().is_none());

        // Set and get
        store
            .set_dream_state("last_dream_at", "2026-03-29T00:00:00Z")
            .unwrap();
        let val = store.get_dream_state("last_dream_at").unwrap();
        assert_eq!(val.as_deref(), Some("2026-03-29T00:00:00Z"));

        // Upsert overwrites
        store
            .set_dream_state("last_dream_at", "2026-03-30T00:00:00Z")
            .unwrap();
        let val = store.get_dream_state("last_dream_at").unwrap();
        assert_eq!(val.as_deref(), Some("2026-03-30T00:00:00Z"));
    }

    #[test]
    fn test_sessions_needing_extraction_empty() {
        let (_dir, store) = test_store();
        let ids = store.sessions_needing_extraction(10).unwrap();
        assert!(ids.is_empty());
    }

    #[test]
    fn test_deductive_observation_with_sources() {
        let (_dir, store) = test_store();
        let source_id1 = Uuid::new_v4();
        let source_id2 = Uuid::new_v4();
        let obs = Observation {
            id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            project_id: None,
            level: ObservationLevel::Deductive,
            content: "Inferred fact from sources".to_string(),
            source_ids: vec![source_id1, source_id2],
            confidence: None,
            times_derived: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        store.insert_observation(&obs).unwrap();

        let list = store
            .list_observations_by_level(ObservationLevel::Deductive, 100)
            .unwrap();
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].source_ids.len(), 2);
        assert!(list[0].source_ids.contains(&source_id1));
        assert!(list[0].source_ids.contains(&source_id2));
    }

    #[test]
    fn test_inductive_observation_with_confidence() {
        let (_dir, store) = test_store();
        let obs = Observation {
            id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            project_id: None,
            level: ObservationLevel::Inductive,
            content: "Pattern detected".to_string(),
            source_ids: vec![Uuid::new_v4(), Uuid::new_v4(), Uuid::new_v4()],
            confidence: Some(ObservationConfidence::Medium),
            times_derived: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        store.insert_observation(&obs).unwrap();

        let list = store
            .list_observations_by_level(ObservationLevel::Inductive, 100)
            .unwrap();
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].confidence, Some(ObservationConfidence::Medium));
    }

    #[test]
    fn test_list_observations_by_project() {
        let (_dir, store) = test_store();
        let project_id = Uuid::new_v4();
        let obs1 = Observation {
            id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            project_id: Some(project_id),
            level: ObservationLevel::Explicit,
            content: "project obs".to_string(),
            source_ids: vec![],
            confidence: None,
            times_derived: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        let obs2 = Observation {
            id: Uuid::new_v4(),
            session_id: Uuid::new_v4(),
            project_id: None,
            level: ObservationLevel::Explicit,
            content: "global obs".to_string(),
            source_ids: vec![],
            confidence: None,
            times_derived: 1,
            created_at: Utc::now(),
            updated_at: Utc::now(),
        };
        store.insert_observation(&obs1).unwrap();
        store.insert_observation(&obs2).unwrap();

        let list = store.list_observations_by_project(project_id).unwrap();
        assert_eq!(list.len(), 1);
        assert_eq!(list[0].content, "project obs");
    }
}
