use std::fs;
use std::io;
use std::path::{Path, PathBuf};

fn collect_store_sources(directory: &Path, files: &mut Vec<PathBuf>) -> io::Result<()> {
    for entry in fs::read_dir(directory)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            collect_store_sources(&path, files)?;
        } else if path.extension().is_some_and(|extension| extension == "rs")
            && path.file_name().is_none_or(|name| name != "tests.rs")
        {
            files.push(path);
        }
    }
    Ok(())
}

fn store_source_digest(manifest_directory: &Path) -> io::Result<String> {
    let workspace = manifest_directory
        .parent()
        .and_then(Path::parent)
        .ok_or_else(|| io::Error::other("rsid-store manifest is not inside the workspace"))?;
    let mut files = Vec::new();
    collect_store_sources(&manifest_directory.join("src/store"), &mut files)?;
    files.extend([
        manifest_directory.join("Cargo.toml"),
        workspace.join("Cargo.lock"),
        workspace.join("rust-toolchain.toml"),
    ]);
    files.sort();

    let mut hasher = blake3::Hasher::new();
    hasher.update(b"rsid-current-schema-template-source-v1\0");
    for path in files {
        let relative = path.strip_prefix(workspace).map_err(io::Error::other)?;
        let relative = relative.to_string_lossy();
        let contents = fs::read(&path)?;
        hasher.update(&(relative.len() as u64).to_le_bytes());
        hasher.update(relative.as_bytes());
        hasher.update(&(contents.len() as u64).to_le_bytes());
        hasher.update(&contents);
        println!("cargo:rerun-if-changed={}", path.display());
    }
    Ok(hasher.finalize().to_hex().to_string())
}

/// Collect `src/store/migrations/vNNN.rs` (one file per schema version) into
/// `$OUT_DIR/store_migrations.rs`: the `include!` of every file, the ordered
/// `MIGRATION_STEPS` runner table, and `LATEST_SCHEMA_VERSION` (the highest
/// version present). Adding a migration is adding one file; no shared list or
/// constant is edited.
fn generate_store_migrations(manifest_directory: &Path, out_directory: &Path) -> io::Result<()> {
    let directory = manifest_directory.join("src/store/migrations");
    let mut versions = Vec::new();
    for entry in fs::read_dir(&directory)? {
        let name = entry?.file_name().to_string_lossy().into_owned();
        let Some(number) = name
            .strip_prefix('v')
            .and_then(|rest| rest.strip_suffix(".rs"))
        else {
            continue;
        };
        let Ok(version) = number.parse::<u32>() else {
            continue;
        };
        if format!("{version:03}") != number {
            return Err(io::Error::other(format!(
                "migration file {name} must be named v{version:03}.rs"
            )));
        }
        versions.push(version);
    }
    versions.sort_unstable();
    if versions.first() != Some(&0) {
        return Err(io::Error::other("store migrations must start at v000.rs"));
    }
    let latest = *versions.last().expect("versions is non-empty");

    let mut source = String::from(
        "// @generated by build.rs from src/store/migrations/v*.rs. Do not edit.\n\n\
         /// Latest schema version applied by `init_schema()`: the highest\n\
         /// `migrations/vNNN.rs`. Released migration DDL, catalog projections and\n\
         /// fingerprints are immutable; add a forward migration file instead.\n",
    );
    source.push_str(&format!(
        "pub const LATEST_SCHEMA_VERSION: i32 = {latest};\n\n"
    ));
    for version in &versions {
        source.push_str(&format!(
            "include!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/src/store/migrations/v{version:03}.rs\"));\n"
        ));
    }
    source.push_str(
        "\n/// Every migration step in ascending version order. Each step gates its own\n\
         /// work on the database's current `user_version`.\n\
         const MIGRATION_STEPS: &[(i32, fn(&Store, i32) -> Result<()>)] = &[\n",
    );
    for version in &versions {
        source.push_str(&format!("    ({version}, Store::migrate_v{version:03}),\n"));
    }
    source.push_str("];\n");
    fs::write(out_directory.join("store_migrations.rs"), source)?;
    // A directory path makes cargo rescan it, so a new file reruns this script.
    println!("cargo:rerun-if-changed={}", directory.display());
    Ok(())
}

// SEAM-GUARD-BEGIN
/// `test-seam` carries fake capabilities and route-validation bypasses; it must
/// never be compiled into a release build. A release-mode test run that needs
/// it opts in explicitly with `RSID_ALLOW_TEST_SEAM_RELEASE=1`.
fn refuse_test_seam_in_release() {
    println!("cargo:rerun-if-env-changed=RSID_ALLOW_TEST_SEAM_RELEASE");
    let seam = std::env::var_os("CARGO_FEATURE_TEST_SEAM").is_some();
    let release = std::env::var("PROFILE").is_ok_and(|profile| profile == "release");
    let allowed = std::env::var("RSID_ALLOW_TEST_SEAM_RELEASE").is_ok_and(|value| value == "1");
    assert!(
        !(seam && release && !allowed),
        "the `test-seam` feature is enabled in a release build; it must never ship \
         (set RSID_ALLOW_TEST_SEAM_RELEASE=1 only for a release-mode test run)"
    );
}
// SEAM-GUARD-END

fn main() {
    refuse_test_seam_in_release();
    let manifest_directory = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("Cargo sets CARGO_MANIFEST_DIR"),
    );
    let digest = store_source_digest(&manifest_directory)
        .expect("hash production Store sources for the test schema-template cache");
    println!("cargo:rustc-env=RSID_TEST_SCHEMA_SOURCE_DIGEST={digest}");

    let out_directory = PathBuf::from(std::env::var_os("OUT_DIR").expect("Cargo sets OUT_DIR"));
    generate_store_migrations(&manifest_directory, &out_directory)
        .expect("generate the store migration list");
}
