// Structural TS codecs/types are generated from the canonical Rust declarations.
// Cross-field rules have independent Rust/TS implementations, exercised by fixtures.
import { readFileSync, writeFileSync } from 'node:fs';
const source = readFileSync(new URL('../../../crates/rsi-common/src/remote_read.rs', import.meta.url), 'utf8');
const definitions = new Map();
function split(s) {
  let depth = 0, start = 0; const out = [];
  for (let i = 0; i < s.length; i++) {
    if ('<({['.includes(s[i])) depth++;
    if ('>)}]'.includes(s[i])) depth--;
    if (s[i] === ',' && depth === 0) { out.push(s.slice(start, i).trim()); start = i + 1; }
  }
  out.push(s.slice(start).trim()); return out.filter(Boolean);
}
function braces(start) {
  let depth = 1, end = start;
  while (depth && ++end < source.length) { if (source[end] === '{') depth++; if (source[end] === '}') depth--; }
  return source.slice(start + 1, end);
}
const primitiveNames = new Set(['DecimalU64', 'DecimalI64', 'WireUuid', 'Timestamp', 'DecisionId', 'OpaqueToken']);
function type(s) {
  s = s.trim();
  if (s === 'bool') return 'boolean';
  if (s === 'u32') return 'integer(0, 4294967295)';
  if (s === 'i32') return 'integer(-2147483648, 2147483647)';
  if (s.startsWith('Text<')) { const [max, nonempty] = split(s.slice(5, -1)); return `text(${max}, ${nonempty !== 'false'})`; }
  for (const [rust, ts] of [['Vec', 'array'], ['Option', 'nullable'], ['Box', 'identity']]) {
    if (s.startsWith(`${rust}<`)) { const t = type(s.slice(rust.length + 1, -1)); return ts === 'identity' ? t : `${ts}(${t})`; }
  }
  return s;
}
function fields(s) {
  return split(s).map(f => {
    const def = f.match(/#\[serde\(default(?:\s*=\s*"([^"]+)")?\)\]/);
    f = f.replace(/#\[serde\([^]*?\)\]/g, '').trim();
    const m = f.match(/^(\w+)\s*:\s*([^]+)$/);
    if (!m) throw Error(`Unrecognized Rust field: ${f}`);
    let t = type(m[2]);
    if (def) {
      const val = def[1]?.startsWith('limit') ? def[1].slice(5) : def[1] === 'attention' ? '"attention"' : m[2] === 'bool' ? 'false' : 'null';
      t = `defaulted(${t}, ${val})`;
    }
    return `${m[1]}: ${t}`;
  });
}
for (const m of source.matchAll(/closed!\(\s*(\w+)\s*\{([^}]+)\}\s*\)/g)) {
  definitions.set(m[1], `oneOf(${JSON.stringify(split(m[2]).map(snake))})`);
}
function snake(s) { return s.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toLowerCase(); }
for (const m of source.matchAll(/labels!\(\s*(\w+)\s*,\s*(\w+)\s*\{([^}]+)\}\s*\)/g)) {
  definitions.set(m[2], `oneOf(${JSON.stringify(split(m[3]))})`);
  definitions.set(m[1], `union([object({state: literal("known"), value: ${m[2]}}), object({state: literal("unknown"), label: text(128, true)})])`);
}
let observation;
for (const m of source.matchAll(/(?:wire|envelope)!\(\s*(\w+)\s*\{/g)) {
  const fs = fields(braces(m.index + m[0].lastIndexOf('{')));
  if (m[1] === 'ObservationV1') observation = fs;
  const all = m[0].startsWith('envelope') ? [...observation, ...fs] : fs;
  definitions.set(m[1], `object({${all.join(', ')}})`);
}
const unionTags = {
  CursorV1: ['kind'],
  ViewReadRequestV1: ['method', 'params', false],
  HistoryWindowV1: ['kind'], ReadRequestV1: ['method', 'params', false],
  HistoryPositionV1: ['state'], DecisionDisplayV1: ['kind'], RetainedDecisionDisplayV1: ['kind'], SelectedDecisionV1: ['state'],
  ReadResponseV1: ['method', 'result', false], SelectionV1: ['kind'], NoticeV1: ['event', 'data'], WireDocumentV1: ['type', 'value'],
};
const objectEnums = new Set();
for (const m of source.matchAll(/object_enum!\s*\{/g)) {
  const name = braces(m.index + m[0].lastIndexOf('{')).match(/pub enum (\w+)\s*\{/)?.[1];
  if (name) objectEnums.add(name);
}
for (const m of source.matchAll(/pub enum (\w+)\s*\{/g)) {
  const body = braces(m.index + m[0].lastIndexOf('{'));
  if (m[1] === 'ReadMethodV1') { definitions.set(m[1], `oneOf(${JSON.stringify(split(body))})`); continue; }
  const tags = unionTags[m[1]];
  if (!tags) throw Error(`Unrecognized Rust enum: ${m[1]}`);
  if (!objectEnums.has(m[1])) throw Error(`Tagged Rust enum must use object_enum!: ${m[1]}`);
  const [tag, content, rename = true] = tags;
  const variants = split(body).map(v => {
    const name = v.match(/^\w+/)?.[0];
    if (!name) throw Error(`Unrecognized variant ${v}`);
    const label = rename ? snake(name) : name;
    let fs = [];
    if (v.includes('{')) fs = fields(v.slice(v.indexOf('{') + 1, v.lastIndexOf('}')));
    else if (v.includes('(')) fs = [`${content}: ${type(v.slice(v.indexOf('(') + 1, v.lastIndexOf(')')))}`];
    return `object({${tag}: literal(${JSON.stringify(label)}), ${fs.join(', ')}})`;
  });
  definitions.set(m[1], `union([${variants.join(', ')}])`);
}
let output = '// Generated by generate.mjs from crates/rsi-common/src/remote_read.rs. Do not edit.\n';
output += 'import { array, boolean, defaulted, define, integer, literal, nullable, object, oneOf, text, union, DecimalU64, DecimalI64, WireUuid, Timestamp, DecisionId, OpaqueToken, type Infer } from "./codec.js";\n';
const emitted = new Set(primitiveNames);
function emit(name) {
  if (emitted.has(name)) return;
  const def = definitions.get(name);
  if (!def) throw Error(`Missing type: ${name}`);
  emitted.add(name);
  for (const token of def.match(/\b\w+V1\b/g) ?? []) if (definitions.has(token)) emit(token);
  output += `export const ${name} = define(${JSON.stringify(name)}, ${def});\nexport type ${name} = Infer<typeof ${name}>;\n`;
}
for (const name of definitions.keys()) emit(name);
output += `export type TypeMap = {${[...definitions.keys()].map(n => `${n}: ${n}`).join('; ')}};\n`;
const path = new URL('src/generated.ts', import.meta.url);
if (process.argv.includes('--check')) {
  if (readFileSync(path, 'utf8') !== output) throw Error('Generated TS codecs are stale');
} else writeFileSync(path, output);
